# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_b_example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62usiness_b_example.proto\x12\x0ekgs.gateway.v1\"s\n\x08RequestB\x12-\n\x05test3\x18\x01 \x01(\x0b\x32\x1c.kgs.gateway.v1.RequestTest3H\x00\x12-\n\x05test4\x18\x02 \x01(\x0b\x32\x1c.kgs.gateway.v1.RequestTest4H\x00\x42\t\n\x07request\"w\n\tResponseB\x12.\n\x05test3\x18\x01 \x01(\x0b\x32\x1d.kgs.gateway.v1.ResponseTest3H\x00\x12.\n\x05test4\x18\x02 \x01(\x0b\x32\x1d.kgs.gateway.v1.ResponseTest4H\x00\x42\n\n\x08response\"\x1c\n\x0cRequestTest3\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\rResponseTest3\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1c\n\x0cRequestTest4\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\rResponseTest4\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\tB\x7f\n\"com.kingsoft.shiyou.kgs.gateway.v1B\x14\x42usinessExampleProtoP\x01ZAgit.shiyou.kingsoft.com/server/kgs-apis/go/kgs/gateway/v1;gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_b_example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.kingsoft.shiyou.kgs.gateway.v1B\024BusinessExampleProtoP\001ZAgit.shiyou.kingsoft.com/server/kgs-apis/go/kgs/gateway/v1;gateway'
  _REQUESTB._serialized_start=44
  _REQUESTB._serialized_end=159
  _RESPONSEB._serialized_start=161
  _RESPONSEB._serialized_end=280
  _REQUESTTEST3._serialized_start=282
  _REQUESTTEST3._serialized_end=310
  _RESPONSETEST3._serialized_start=312
  _RESPONSETEST3._serialized_end=361
  _REQUESTTEST4._serialized_start=363
  _REQUESTTEST4._serialized_end=391
  _RESPONSETEST4._serialized_start=393
  _RESPONSETEST4._serialized_end=442
# @@protoc_insertion_point(module_scope)
