# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business_a_example.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62usiness_a_example.proto\x12\x0ekgs.gateway.v1\"\x1c\n\x0cRequestTest1\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\rResponseTest1\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"\x1c\n\x0cRequestTest2\x12\x0c\n\x04text\x18\x01 \x01(\t\"1\n\rResponseTest2\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\x0c\n\x04text\x18\x02 \x01(\t\"6\n\nNoticeTest\x12\x12\n\nservice_id\x18\x01 \x01(\t\x12\t\n\x01\x61\x18\x02 \x01(\t\x12\t\n\x01\x62\x18\x03 \x01(\tB\x7f\n\"com.kingsoft.shiyou.kgs.gateway.v1B\x14\x42usinessExampleProtoP\x01ZAgit.shiyou.kingsoft.com/server/kgs-apis/go/kgs/gateway/v1;gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_a_example_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.kingsoft.shiyou.kgs.gateway.v1B\024BusinessExampleProtoP\001ZAgit.shiyou.kingsoft.com/server/kgs-apis/go/kgs/gateway/v1;gateway'
  _REQUESTTEST1._serialized_start=44
  _REQUESTTEST1._serialized_end=72
  _RESPONSETEST1._serialized_start=74
  _RESPONSETEST1._serialized_end=123
  _REQUESTTEST2._serialized_start=125
  _REQUESTTEST2._serialized_end=153
  _RESPONSETEST2._serialized_start=155
  _RESPONSETEST2._serialized_end=204
  _NOTICETEST._serialized_start=206
  _NOTICETEST._serialized_end=260
# @@protoc_insertion_point(module_scope)
