# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62usiness.proto\x12\x0ekgs.gateway.v1\"V\n\x0f\x42usinessRequest\x12(\n\x07session\x18\x01 \x01(\x0b\x32\x17.kgs.gateway.v1.Session\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\":\n\x10\x42usinessResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"\x80\x01\n\x07Session\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12/\n\x04meta\x18\x03 \x03(\x0b\x32!.kgs.gateway.v1.Session.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"z\n\rNotifyRequest\x12(\n\x07session\x18\x01 \x01(\x0b\x32\x17.kgs.gateway.v1.Session\x12\x38\n\x0buser_notify\x18\x02 \x01(\x0b\x32!.kgs.gateway.v1.UserNotifyRequestH\x00\x42\x05\n\x03req\"R\n\x0eNotifyResponse\x12\x39\n\x0buser_notify\x18\x01 \x01(\x0b\x32\".kgs.gateway.v1.UserNotifyResponseH\x00\x42\x05\n\x03rsp\"9\n\x11UserNotifyRequest\x12$\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x15.kgs.gateway.v1.Event\"$\n\x12UserNotifyResponse\x12\x0e\n\x06result\x18\x01 \x01(\r\"S\n\x0cGatewayLogic\x12:\n\x10set_user_session\x18\x01 \x01(\x0b\x32\x1e.kgs.gateway.v1.SetUserSessionH\x00\x42\x07\n\x05logic\"u\n\x0eSetUserSession\x12\x36\n\x04meta\x18\x01 \x03(\x0b\x32(.kgs.gateway.v1.SetUserSession.MetaEntry\x1a+\n\tMetaEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01* \n\x05\x45vent\x12\n\n\x06ONLINE\x10\x00\x12\x0b\n\x07OFFLINE\x10\x01\x32\xb3\x01\n\x0f\x42usinessService\x12U\n\x0c\x43\x61llBusiness\x12\x1f.kgs.gateway.v1.BusinessRequest\x1a .kgs.gateway.v1.BusinessResponse\"\x00\x30\x01\x12I\n\x06Notify\x12\x1d.kgs.gateway.v1.NotifyRequest\x1a\x1e.kgs.gateway.v1.NotifyResponse\"\x00\x42x\n\"com.kingsoft.shiyou.kgs.gateway.v1B\rBusinessProtoP\x01ZAgit.shiyou.kingsoft.com/server/kgs-apis/go/kgs/gateway/v1;gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\"com.kingsoft.shiyou.kgs.gateway.v1B\rBusinessProtoP\001ZAgit.shiyou.kingsoft.com/server/kgs-apis/go/kgs/gateway/v1;gateway'
  _SESSION_METAENTRY._options = None
  _SESSION_METAENTRY._serialized_options = b'8\001'
  _SETUSERSESSION_METAENTRY._options = None
  _SETUSERSESSION_METAENTRY._serialized_options = b'8\001'
  _EVENT._serialized_start=822
  _EVENT._serialized_end=854
  _BUSINESSREQUEST._serialized_start=34
  _BUSINESSREQUEST._serialized_end=120
  _BUSINESSRESPONSE._serialized_start=122
  _BUSINESSRESPONSE._serialized_end=180
  _SESSION._serialized_start=183
  _SESSION._serialized_end=311
  _SESSION_METAENTRY._serialized_start=268
  _SESSION_METAENTRY._serialized_end=311
  _NOTIFYREQUEST._serialized_start=313
  _NOTIFYREQUEST._serialized_end=435
  _NOTIFYRESPONSE._serialized_start=437
  _NOTIFYRESPONSE._serialized_end=519
  _USERNOTIFYREQUEST._serialized_start=521
  _USERNOTIFYREQUEST._serialized_end=578
  _USERNOTIFYRESPONSE._serialized_start=580
  _USERNOTIFYRESPONSE._serialized_end=616
  _GATEWAYLOGIC._serialized_start=618
  _GATEWAYLOGIC._serialized_end=701
  _SETUSERSESSION._serialized_start=703
  _SETUSERSESSION._serialized_end=820
  _SETUSERSESSION_METAENTRY._serialized_start=268
  _SETUSERSESSION_METAENTRY._serialized_end=311
  _BUSINESSSERVICE._serialized_start=857
  _BUSINESSSERVICE._serialized_end=1036
# @@protoc_insertion_point(module_scope)
