# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: business.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x62usiness.proto\x12\x0cproq.gateway\"T\n\x0f\x42usinessRequest\x12&\n\x07session\x18\x01 \x01(\x0b\x32\x15.proq.gateway.Session\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\":\n\x10\x42usinessResponse\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0b\n\x03\x63md\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"~\n\x07Session\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12-\n\x04info\x18\x03 \x03(\x0b\x32\x1f.proq.gateway.Session.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"v\n\rNotifyRequest\x12&\n\x07session\x18\x01 \x01(\x0b\x32\x15.proq.gateway.Session\x12\x36\n\x0buser_notify\x18\x02 \x01(\x0b\x32\x1f.proq.gateway.UserNotifyRequestH\x00\x42\x05\n\x03req\"P\n\x0eNotifyResponse\x12\x37\n\x0buser_notify\x18\x01 \x01(\x0b\x32 .proq.gateway.UserNotifyResponseH\x00\x42\x05\n\x03rsp\"7\n\x11UserNotifyRequest\x12\"\n\x05\x65vent\x18\x01 \x01(\x0e\x32\x13.proq.gateway.Event\"$\n\x12UserNotifyResponse\x12\x0e\n\x06result\x18\x01 \x01(\r* \n\x05\x45vent\x12\n\n\x06ONLINE\x10\x00\x12\x0b\n\x07OFFLINE\x10\x01\x32\xab\x01\n\x0f\x42usinessService\x12Q\n\x0c\x43\x61llBusiness\x12\x1d.proq.gateway.BusinessRequest\x1a\x1e.proq.gateway.BusinessResponse\"\x00\x30\x01\x12\x45\n\x06Notify\x12\x1b.proq.gateway.NotifyRequest\x1a\x1c.proq.gateway.NotifyResponse\"\x00\x42:Z8git.shiyou.kingsoft.com/proq/protocol/go/gateway;gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'business_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8git.shiyou.kingsoft.com/proq/protocol/go/gateway;gateway'
  _SESSION_INFOENTRY._options = None
  _SESSION_INFOENTRY._serialized_options = b'8\001'
  _EVENT._serialized_start=603
  _EVENT._serialized_end=635
  _BUSINESSREQUEST._serialized_start=32
  _BUSINESSREQUEST._serialized_end=116
  _BUSINESSRESPONSE._serialized_start=118
  _BUSINESSRESPONSE._serialized_end=176
  _SESSION._serialized_start=178
  _SESSION._serialized_end=304
  _SESSION_INFOENTRY._serialized_start=261
  _SESSION_INFOENTRY._serialized_end=304
  _NOTIFYREQUEST._serialized_start=306
  _NOTIFYREQUEST._serialized_end=424
  _NOTIFYRESPONSE._serialized_start=426
  _NOTIFYRESPONSE._serialized_end=506
  _USERNOTIFYREQUEST._serialized_start=508
  _USERNOTIFYREQUEST._serialized_end=563
  _USERNOTIFYRESPONSE._serialized_start=565
  _USERNOTIFYRESPONSE._serialized_end=601
  _BUSINESSSERVICE._serialized_start=638
  _BUSINESSSERVICE._serialized_end=809
# @@protoc_insertion_point(module_scope)
