# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63lient.proto\x12\x0cproq.gateway\"\xa7\x01\n\x07Request\x12+\n\x05login\x18\x01 \x01(\x0b\x32\x1a.proq.gateway.RequestLoginH\x00\x12\x33\n\theartbeat\x18\x02 \x01(\x0b\x32\x1e.proq.gateway.RequestHeartbeatH\x00\x12/\n\x07\x66orward\x18\x03 \x01(\x0b\x32\x1c.proq.gateway.RequestForwardH\x00\x42\t\n\x07request\"\xd4\x01\n\x08Response\x12,\n\x05login\x18\x01 \x01(\x0b\x32\x1b.proq.gateway.ResponseLoginH\x00\x12\x34\n\theartbeat\x18\x02 \x01(\x0b\x32\x1f.proq.gateway.ResponseHeartbeatH\x00\x12\x30\n\x07\x66orward\x18\x03 \x01(\x0b\x32\x1d.proq.gateway.ResponseForwardH\x00\x12&\n\x06notice\x18\x04 \x01(\x0b\x32\x14.proq.gateway.NoticeH\x00\x42\n\n\x08response\"~\n\x0cRequestLogin\x12\r\n\x05token\x18\x01 \x01(\t\x12\x32\n\x04info\x18\x02 \x03(\x0b\x32$.proq.gateway.RequestLogin.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1f\n\rResponseLogin\x12\x0e\n\x06result\x18\x01 \x01(\r\"!\n\x10RequestHeartbeat\x12\r\n\x05milli\x18\x01 \x01(\x03\"\"\n\x11ResponseHeartbeat\x12\r\n\x05milli\x18\x01 \x01(\x03\"+\n\x0eRequestForward\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\",\n\x0fResponseForward\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"<\n\x06Notice\x12\x0c\n\x04\x63ode\x18\x01 \x01(\r\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x13\n\x0brequest_cmd\x18\x03 \x01(\tB:Z8git.shiyou.kingsoft.com/proq/protocol/go/gateway;gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'client_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8git.shiyou.kingsoft.com/proq/protocol/go/gateway;gateway'
  _REQUESTLOGIN_INFOENTRY._options = None
  _REQUESTLOGIN_INFOENTRY._serialized_options = b'8\001'
  _REQUEST._serialized_start=31
  _REQUEST._serialized_end=198
  _RESPONSE._serialized_start=201
  _RESPONSE._serialized_end=413
  _REQUESTLOGIN._serialized_start=415
  _REQUESTLOGIN._serialized_end=541
  _REQUESTLOGIN_INFOENTRY._serialized_start=498
  _REQUESTLOGIN_INFOENTRY._serialized_end=541
  _RESPONSELOGIN._serialized_start=543
  _RESPONSELOGIN._serialized_end=574
  _REQUESTHEARTBEAT._serialized_start=576
  _REQUESTHEARTBEAT._serialized_end=609
  _RESPONSEHEARTBEAT._serialized_start=611
  _RESPONSEHEARTBEAT._serialized_end=645
  _REQUESTFORWARD._serialized_start=647
  _REQUESTFORWARD._serialized_end=690
  _RESPONSEFORWARD._serialized_start=692
  _RESPONSEFORWARD._serialized_end=736
  _NOTICE._serialized_start=738
  _NOTICE._serialized_end=798
# @@protoc_insertion_point(module_scope)
