# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncode.proto\x12\x0cproq.gateway*\x82\x03\n\x04\x43ode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x04\x46\x41IL\x10\xe8\x07\x12\x12\n\rINVALID_PARAM\x10\xe9\x07\x12\x0e\n\tPROTO_ERR\x10\xea\x07\x12\x17\n\x12MAX_CONNECTION_ERR\x10\xd0\x0f\x12\x10\n\x0bJWT_EXPIRED\x10\xd1\x0f\x12\x10\n\x0bJWT_INVALID\x10\xd2\x0f\x12\x0f\n\nLOGIN_FAIL\x10\xd3\x0f\x12\x19\n\x14GATEWAY_INTERNAL_ERR\x10\xb4\x10\x12\x13\n\x0eLOGIN_REPLACED\x10\xb5\x10\x12\x19\n\x14\x42USINESS_SERVICE_ERR\x10\xb6\x10\x12\x1d\n\x18\x42USINESS_SERVICE_NO_NODE\x10\xb7\x10\x12\x18\n\x13PASSIVE_SERVICE_ERR\x10\xb8\x10\x12\x10\n\x0bINVALID_CMD\x10\xb9\x10\x12\x1a\n\x15\x43LOSE_USER_CONNECTION\x10\xba\x10\x12\x15\n\x10SET_USER_SERVICE\x10\xbb\x10\x12\x13\n\x0eUSER_NOT_LOGIN\x10\x98\x11\x12\x12\n\rNoGatewayNode\x10\xb8\x17\x42:Z8git.shiyou.kingsoft.com/proq/protocol/go/gateway;gatewayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z8git.shiyou.kingsoft.com/proq/protocol/go/gateway;gateway'
  _CODE._serialized_start=29
  _CODE._serialized_end=415
# @@protoc_insertion_point(module_scope)
