# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: code.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncode.proto\x12\x04game*\xaf\x01\n\x04\x43ode\x12\x0b\n\x07SUCCESS\x10\x00\x12\t\n\x04\x46\x41IL\x10\xe8\x07\x12\x12\n\rINVALID_PARAM\x10\xe9\x07\x12\x0e\n\tPROTO_ERR\x10\xea\x07\x12\x0f\n\nCONFIG_ERR\x10\xeb\x07\x12\x17\n\x12RESOURCE_NOTENOUGH\x10\xec\x07\x12\x16\n\x11\x46UNCTION_NOT_OPEN\x10\xed\x07\x12\x13\n\x0eITEM_NOTENOUGH\x10\xcc\x08\x12\x14\n\x0fITEM_CANNOT_USE\x10\xcd\x08*m\n\tGachaType\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0b\x46RIEND_SHIP\x10\x01\x12\n\n\x06\x43OMMON\x10\x02\x12\t\n\x05\x43\x41MP1\x10\x03\x12\t\n\x05\x43\x41MP2\x10\x04\x12\t\n\x05\x43\x41MP3\x10\x05\x12\t\n\x05\x43\x41MP4\x10\x06\x12\r\n\tASTROLOGY\x10\x07*D\n\x0fHeroBaseQuality\x12\x10\n\x0cQuality_NONE\x10\x00\x12\t\n\x05GREEN\x10\x01\x12\x08\n\x04\x42LUE\x10\x02\x12\n\n\x06PURPLE\x10\x04\x42\x32Z0git.shiyou.kingsoft.com/proq/qserver/api/go/gameb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z0git.shiyou.kingsoft.com/proq/qserver/api/go/game'
  _CODE._serialized_start=21
  _CODE._serialized_end=196
  _GACHATYPE._serialized_start=198
  _GACHATYPE._serialized_end=307
  _HEROBASEQUALITY._serialized_start=309
  _HEROBASEQUALITY._serialized_end=377
# @@protoc_insertion_point(module_scope)
