# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hero.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhero.proto\x12\x05table\x1a google/protobuf/descriptor.proto\"\xe1\x01\n\x04Hero\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03\x63id\x18\x02 \x01(\t\x12\x13\n\x0b\x63reate_time\x18\x03 \x01(\r\x12\x0b\n\x03\x65vo\x18\x04 \x01(\r\x12\x10\n\x08init_evo\x18\x05 \x01(\r\x12\n\n\x02lv\x18\x06 \x01(\r\x12\x0b\n\x03\x63lv\x18\x07 \x01(\r\x12\x0e\n\x06\x63ombat\x18\x08 \x01(\x04\x12\x0e\n\x06locked\x18\t \x01(\x08\x12%\n\x05\x61ttrs\x18\n \x03(\x0b\x32\x16.table.Hero.AttrsEntry\x1a,\n\nAttrsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x42\tZ\x07.;tableb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hero_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\007.;table'
  _HERO_ATTRSENTRY._options = None
  _HERO_ATTRSENTRY._serialized_options = b'8\001'
  _HERO._serialized_start=56
  _HERO._serialized_end=281
  _HERO_ATTRSENTRY._serialized_start=237
  _HERO_ATTRSENTRY._serialized_end=281
# @@protoc_insertion_point(module_scope)
